---
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
#    ports:
#      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@umami_db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: 9297bc8e9a53db6bd90d67bc40fce8c11e513ef5c913d27fe26e28838312408e
    restart: always
    depends_on:
      umami_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  umami_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  umami-db-data:

networks:
  default:
    external: true
    name: firehose_nginx
